"""Update User model

Revision ID: 42e020de1d2f
Revises: cc1caf45eb81

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42e020de1d2f"
down_revision: Union[str, None] = "cc1caf45eb81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "call_keypoints",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "call_keypoints",
        "analysis_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "calls",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "calls",
        "agent_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "detected_intents",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "detected_intents",
        "analysis_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "extracted_entities",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "extracted_entities",
        "analysis_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "identified_issues",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "identified_issues",
        "analysis_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "recommended_actions",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "recommended_actions",
        "analysis_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "speech_analysis",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "speech_analysis",
        "call_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.add_column("users", sa.Column("first_name", sa.String(), nullable=False))
    op.add_column("users", sa.Column("last_name", sa.String(), nullable=False))
    op.add_column("users", sa.Column("password", sa.String(), nullable=False))
    op.alter_column(
        "users",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "LastName")
    op.drop_column("users", "FirstName")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("FirstName", sa.VARCHAR(), nullable=False))
    op.add_column("users", sa.Column("LastName", sa.VARCHAR(), nullable=False))
    op.add_column("users", sa.Column("hashed_password", sa.VARCHAR(), nullable=False))
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.drop_column("users", "password")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.alter_column(
        "speech_analysis",
        "call_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "speech_analysis",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "recommended_actions",
        "analysis_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "recommended_actions",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "identified_issues",
        "analysis_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "identified_issues",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "extracted_entities",
        "analysis_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "extracted_entities",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "detected_intents",
        "analysis_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "detected_intents",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "calls",
        "agent_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "calls",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "call_keypoints",
        "analysis_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "call_keypoints",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
