"""Add file_name field

Revision ID: 4bb7c2e9c8da
Revises: 6e749dd6fb30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb7c2e9c8da'
down_revision: Union[str, None] = '6e749dd6fb30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. add column nullable first
    op.add_column('calls', sa.Column('file_name', sa.String(), nullable=True))

    # 2. backfill data
    # assumes file_name should mirror celery_task_id
    op.execute("""
        UPDATE calls
        SET file_name = celery_task_id
        WHERE file_name IS NULL
    """)

    # 3. set NOT NULL
    op.alter_column('calls', 'file_name', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'file_name')
    # ### end Alembic commands ###
