"""add_celery_task_id_column

Revision ID: 6b1e4c5ba130
Revises: 78583dbaa39a

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b1e4c5ba130"
down_revision: Union[str, None] = "78583dbaa39a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("calls", sa.Column("celery_task_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("calls", "celery_task_id")
    # ### end Alembic commands ###
