"""add_call_status

Revision ID: 78583dbaa39a
Revises: 42e020de1d2f

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78583dbaa39a"
down_revision: Union[str, None] = "42e020de1d2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("calls", sa.Column("status", sa.String(), nullable=False))
    op.alter_column(
        "calls",
        "call_duration",
        existing_type=sa.INTEGER(),
        type_=sa.Double(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "calls",
        "call_duration",
        existing_type=sa.Double(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("calls", "status")
    # ### end Alembic commands ###
